### ISSUE TITLE
Comments to exercise 2

### ISSUE THREAD

**Issue by lunactic** [neuperc/PR_TheBlueGuys#1]
Please don't hide your results in the code files.

solid code, with good use of provided tools.

**Comment by fmSterio** [comment]
@lunactic Could you please mention what do you mean exactly?

Do you mean for the commented part ?

% ****Here I have tested the best K for cross validaiton betweem  range 5:15 and
% it gives that 9 and 10 gives better results. Is is possible to make it
% automatic to select best K for a range, but I've just avoided 
% computational cost.
% k | Linear   |  RBF 
%-----------------------
% 5-  95.0500   95.5500
% 6-  95.1000   95.0500......

**Comment by lunactic** [comment]
@fmSterio Excatly, it would be nice if you would put that into a separate result.txt file or something like this so I know where to look for the results.

**Comment by fmSterio** [comment]
@lunactic Okay, but that text was just the part to show why I've choose k=10

The overall results are shown on the screen when you run the code.
